### ISSUE TITLE
User rights change for edited yaml file

### ISSUE THREAD

**Issue by tamimology** [htmltiger/config-editor-card#1]
This is wonderful integration, very useful for me, especially since I do not need to expose any special ports to edit any YAML file. I am using Docker on synology. The only issue I found is that once I save a YAML file, the user rights of that file are changed to root/root, which does not allow me to edit it back in VSCode, as it requires 1000/1000 user set on it.

**Comment by htmltiger** [comment]
Can you please try and edit 
`custom_components/config_editor/__init__.py`
Line 78 and change 644 to 666, restart ha

**Comment by tamimology** [comment]
Awesome, this worked as charm now

Thanks mate
