### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by 03397** [htmltiger/config-editor-card#11]
I have successfully installed through hacs the config editor but after I add it in my configuration.yaml the config_editor line I am getting an error saying
Integration error: config_editor - Integration 'config_editor' not found.

Any thoughts?

**Comment by htmltiger** [comment]
I had same issue with nodered integration today.
Its hacs issue, update hacs, restart ha, and redownload

**Comment by 03397** [comment]
I had this issue for sometime now. 
It's just today I found time to open the ticket.
HACS is up to date and config editor is 1.7 version

**Comment by htmltiger** [comment]
Do the manual installation.
custom_components folder should have the config_editor folder as in github code

**Comment by 03397** [comment]
But then I will need to manually  maintain this correct?

Can't we troubleshoot to see what is happening here?

**Comment by htmltiger** [comment]
Have you installed both the card and helper?
https://github.com/htmltiger/config-editor

**Comment by htmltiger** [comment]
1.7 is this card
2.1 is helper

**Comment by htmltiger** [comment]
Please read the installation instructions for both addon on readme

**Comment by 03397** [comment]
No, I have installed whatever was in HACS following the instructions. I have not installed helper. Let me check

**Comment by 03397** [comment]
There were no instructions about the helper.
I have installed it from the hacs inside the integration. 

Thanks for your help

**Comment by htmltiger** [comment]
Step 1 is the helper
