### ISSUE TITLE
Full screen width

### ISSUE THREAD

**Issue by 03397** [htmltiger/config-editor-card#14]
Is there a way that the config edit is wider so that it can use my whole window  width?
See below

![image](https://user-images.githubusercontent.com/6150853/149825334-5cd48303-8f66-42fb-ade1-6ba06a4f4cae.png)

**Comment by htmltiger** [comment]
have you tried panel mode?
![screen](https://user-images.githubusercontent.com/1429451/149828939-d35e3c5b-6590-44df-ad0a-29542ee91e5c.png)

**Comment by 03397** [comment]
Excellent my friend
Thanks a lot.
