### ISSUE TITLE
Feature Request: python_scripts

### ISSUE THREAD

**Issue by embeddeddev** [htmltiger/config-editor-card#15]
It would be very useful, if the ```.py```-Scripts located in ```python_scripts``` sub-directory , that are parsed by the ```python_script``` integration (https://www.home-assistant.io/integrations/python_script/), would be editable.

**Comment by htmltiger** [comment]
I have updated to support more filetypes.
Please upgrade card and the integration helper to check

**Comment by embeddeddev** [comment]
Works like a charm!
Thanx for the quick reaction and good work!
