### ISSUE TITLE
Fix location for filetype and plain text

### ISSUE THREAD

**Issue by tamimology** [htmltiger/config-editor-card#18]
Again, the file type drop down and plain text checkbox moves in accordance to the opened file code lines.

Could be more useful if fixed on top kr bottom regardless of file length

![Screenshot_20220119-010255_Home Assistant](https://user-images.githubusercontent.com/90429593/149952555-658957eb-c64c-474d-97a8-7f8c10aaf893.png)
![Screenshot_20220119-010219_Home Assistant](https://user-images.githubusercontent.com/90429593/149952572-10c14e43-57f2-4c2b-a32b-f430597d7469.png)
![Screenshot_20220119-010235_Home Assistant](https://user-images.githubusercontent.com/90429593/149952599-66045bfe-4cb1-42fa-b983-c396218b7a7b.png)
![Screenshot_20220119-010340_Home Assistant](https://user-images.githubusercontent.com/90429593/149952613-75e3dc6d-5445-4fa3-944e-c9d36739d5d0.png)

**Comment by htmltiger** [comment]
I have moved it to top but keeping everything on fixed position will restrict the available editing space on mobile device
