### ISSUE TITLE
Mobile view

### ISSUE THREAD

**Issue by tamimology** [htmltiger/config-editor-card#2]
When using on movile device (I have Samsung A52 5G), when ever I select the first of the line, the whole view is moved (shifted) to the left side by at least 3 to 3 columns which I cannot see if I select the correct position or not. I have to move the view to the right to check.

Bit annoying if trying to comment several lines by #

**Comment by htmltiger** [comment]
I have just tried it and you are right!

It has the same bugs as any other code editor in Home Assistant.
It needs to be fixed in the core or frontend.

It may fix the issue if we use plain textarea but it would not have the code highlighter.

**Comment by htmltiger** [comment]
Try login in chrome and choose "Desktop site" from 3 dots, it worked fine here

**Comment by tamimology** [comment]
No keep the text with colouring. Hope HA fixes this with time

Thanks, really useful card I was looking for since long to use on mobile as VSCode is running soo bad on phones
