### ISSUE TITLE
Since v3, keeps failing to load

### ISSUE THREAD

**Issue by GRiDlockUK** [htmltiger/config-editor-card#22]
worked once then has failed since - just says "LIST LOADING"
- installed by HACS on docker installation - subfolder has usual 3 files
- configuration.yaml has config_editor:

**Comment by htmltiger** [comment]
have you updated https://github.com/htmltiger/config-editor to 3.x?

**Comment by GRiDlockUK** [comment]
Yes - both are at latest version.

**Comment by htmltiger** [comment]
Seems like caching issue, have you tried it on a different device or browser?
What browser are you using? any errors in console? (right click and choose inspect or F12) also check loaded config editor version in there.

I have just tried it on a brand new installation of HA and it loads fine.

**Comment by GRiDlockUK** [comment]
tried different devices/browsers - restarted HA etc.  Maybe its as I'm running HA container (in docker)?  V2 was great, no issue. V3 seemed to work the once (and was fab) but after a reboot its just stuck "loading files". Will tinker and confirm when solved

**Comment by u8915055** [comment]
Just letting you know that i had this same problem on a mac running chrome. I cleared the browser cache and it works fine now.
