### ISSUE TITLE
ENHANCEMENT - Themes/font sizes

### ISSUE THREAD

**Issue by wheindl** [htmltiger/config-editor-card#24]
I have recently begun using the config editor card and find it both quicker and more convenient than the editor add-in.  I have two related suggestions for new features.  The first would be the ability to change the font size (it is a bit too small for me, but everyone's different).  The second would be some provision for themes, as in the editor add-in, VSCode, and other programmer editors.

**Comment by htmltiger** [comment]
added font size in v3.10

**Comment by wheindl** [comment]
Awesome!  Works and looks great. Walter E. Heindl112 Harvard Avenue, Swarthmore, Pennsylvania 193203080 Batally Court, The Villages, Florida 32162(610) 563-6450 From: htmltigerSent: Thursday, March 3, 2022 2:43 PMTo: htmltiger/config-editor-cardCc: wheindl; AuthorSubject: Re: [htmltiger/config-editor-card] ENHANCEMENT - Themes/font sizes (Issue #24) Closed #24.—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***> 

	
        
		Virus-free. www.avast.com
