### ISSUE TITLE
cannot type using Safari 15.2

### ISSUE THREAD

**Issue by leonardpitzu** [htmltiger/config-editor-card#26]
I can edit file in the sense of deleting lines and pressing return. Typing letters is not working.
Using Edge everything works as expected.
I am using MacOS BigSur as the underlying platform.

**Comment by htmltiger** [comment]
No idea about it but use plain text/basic editor checkbox and see it that makes usable.

**Comment by leonardpitzu** [comment]
Already tried it and it is not working. Same issue on iPadOS, iOS and MacOS

**Comment by htmltiger** [comment]
I have tried it on a ipad mini safari browser and the basic worked fine.

clear the cache (or try in private browsing) and see if it works

**Comment by leonardpitzu** [comment]
it was the ad blocker... weird but without it, it works.
