### ISSUE TITLE
ENHANCEMENT Screen Orientation 

### ISSUE THREAD

**Issue by tamimology** [htmltiger/config-editor-card#27]
When rotating mobile phone, the view doesn't expand to fill up the full orientation. It would be more convenient if it does specifically if a lpng code line to be seen

![Screenshot_20220130-001316_Home Assistant](https://user-images.githubusercontent.com/90429593/151662389-d9572e8c-448b-4da4-bd86-e784a6655c81.png)

**Comment by htmltiger** [comment]
it works fine here.

have a look here
https://github.com/htmltiger/config-editor-card/issues/14

**Comment by tamimology** [comment]
Perfect
Confirm it works as a charm
Thanks
