### ISSUE TITLE
How to add to sidebar

### ISSUE THREAD

**Issue by oywino** [htmltiger/config-editor-card#29]
I have apparently managed to install ;
1. Integrations
![image](https://user-images.githubusercontent.com/18447119/153278875-7b6a62c5-ffb4-4ae5-b6e6-ff93fdb573cf.png)
and
2. Frontend
![image](https://user-images.githubusercontent.com/18447119/153279051-5997f0de-812b-42e7-b5d3-d196e20c003d.png)

But how do I add an icon to the sidebar to launch the editor?
The docs says:
![image](https://user-images.githubusercontent.com/18447119/153279294-b68d69d2-f9b6-4bac-be8e-f43514b766b0.png)
But "create a new tab" is not a valid option under `Configuration > Dashboards > + Add dashboard`  Instead, it requires a URL.
What URL should be added here?  
`type: custom:config-editor-card` is not a valid URL syntax.

Please help.
(All my systems are updated to the latest version, including HA, HACS and the config-editor itself.)

**Comment by htmltiger** [comment]
![image-62](https://user-images.githubusercontent.com/1429451/153308973-e342f0c7-0668-4083-a8d9-704576572127.png)

Edit:
Url needs to be lovelace-editor

**Comment by oywino** [comment]
Even if I change the URL to `lovelace-editor` it still doesn't work.

**Comment by htmltiger** [comment]
Do you know how to create a new tab ?
3 dots  edit  take over blank

**Comment by oywino** [comment]
I'm sorry - I do not understand what you mean:  "3 dots edit take over blank"  ?

**Comment by htmltiger** [comment]
![chrome-capture](https://user-images.githubusercontent.com/1429451/153445708-5a7269b8-a0f0-46dd-9394-12f11b6c4f1b.png)
![chrome-capture (1)](https://user-images.githubusercontent.com/1429451/153445720-7bc7506d-a799-4b47-a826-ab046f6d7872.png)
![chrome-capture](https://user-images.githubusercontent.com/1429451/153445732-e0b77497-7bca-4b73-a156-e0a56c0a8bff.gif)

View type: panel mode (1 card)  
`+ Add card`
Custom: config-editor-card

**Comment by oywino** [comment]
Yes. That worked. Thank you very much.
(But you should update the README.md  -  I would never have figured this one out on my own)  😉

One question out of curiosity; Why is it necessary to add the line `config_editor:` to configuration.yaml ?
Is this something you've decided on, or is it a requirement by design from the HA dev team and thus something you could not skip?

**Comment by oywino** [comment]
I wrote a "guide" mainly to improve my own understanding. If you don't mind, I'd like to publish it on Reddit ?
[How to add Config Editor to HA.pdf](https://github.com/htmltiger/config-editor-card/files/8043991/How.to.add.Config.Editor.to.HA.pdf)

**Comment by htmltiger** [comment]
Sure it would help others

**Comment by warwert123** [comment]
Hello, I wnat to install "Config Editor" and "Config-Editor-Card"  manually without "HACS" .
Now, I can install "Config Editor" through your step 1, and I can see it on the dashboard, it seems to work. 
But when I install  "Config-Editor-Card" through your step 2, I couldn't find it in the selection of "+Add card",
and I couldn't search it manully either. I don't complete the step 2  {add url /local/config-editor-card.js?v=1 from Configuration -> Lovelace Dashboards -> Resources panel when not using YAML mode } , I don't understand what it means.
Can you help me to solve it ? Please and thank you...

**Comment by htmltiger** [comment]
![5c6109540184dac5e5cf347b1f1feb71b0bad0df](https://user-images.githubusercontent.com/1429451/158922796-67abfc21-729b-49d3-af6f-15bd6d018b0a.png)
https://community.home-assistant.io/t/adding-resources-to-lovelace/180729/9

**Comment by warwert123** [comment]
Thank you so much, your guide was helpful.
Now, it can work!
I also check  "Lovelace: Custom Cards" and "Registering Resources"  of
official documents, maybe it can help somebody. 
Thanks, again!

https://developers.home-assistant.io/docs/frontend/custom-ui/registering-resources

**Comment by Yonny24** [comment]
I've reached the step of adding the Custom: config-editor-card but the card is not listed. I've added the config_editor: to the config yaml, restarted etc but do not have the option of this card available on the new dashboard I created.

**Comment by htmltiger** [comment]
Have you completed step 1?
Seems like you have started from step 2

**Comment by Yonny24** [comment]
Thanks did not realize I needed to add the frontend in addition to the integration. Thought it was one or the other.
Card is selectable now thanks

**Comment by Macleykun** [comment]
Hello!
I tried to do the steps (both readme and pdf) But somehow i can't seem to get the panel to show up. I'll list what i have done:
![image](https://user-images.githubusercontent.com/26381427/177391751-932033e6-2486-414b-b33b-e8407d9aff71.png)
Both seem to be installed trough HACS.

I also restarted a few times, and included and removed config_editor: in my configuration.yml (i know this file also works, as i added a few services and they also work).
![image](https://user-images.githubusercontent.com/26381427/177392126-b51e2dc2-24b5-47b1-95b6-828b348fdb7e.png)
The dashboard is also edit to panel 1 card.
![image](https://user-images.githubusercontent.com/26381427/177392190-e8212f56-abdb-44a6-b78a-aaa7730269f1.png)
I don't see the card anywhere and i'm sure i followed all the steps.

You have any suggetions what i could try to get it to work? Appricate ya work so far :)

**Comment by htmltiger** [comment]
![Developer Tools – Home Assistant](https://user-images.githubusercontent.com/1429451/177392767-4bb6cb44-c32c-411b-a061-6b0230d892ed.png)
check if the addon is installed, seems like missing `config_editor:`

it could be that the card is not loaded, clear cache or try in different browser.
also check if  `/config/www/community/config-editor-card/config-editor-card.js` exists

**Comment by Macleykun** [comment]
![image](https://user-images.githubusercontent.com/26381427/177408429-ab5924f9-a232-49ef-b4da-55a6b504ba77.png)

Indeed, so i went into incognito and suddenly it was just there, i even did crtl F5 to refresh withoud cache but to no avail.
Thank you so much! Especially for the incredible fast response!

**Comment by JeffersM1** [comment]
I was able to install, and I can edit the configuration.yaml file.  How can I see and select a yaml file in a subfolder in the the blueprints folder?

**Comment by blb4github** [comment]
thanks @oywino for writing that guide, I would never have got it installed and working without.

**Comment by oywino** [comment]
> thanks @oywino for writing that guide, I would never have got it installed and working without.

You're welcome. Have fun 😊

**Comment by ND-LJQ** [comment]
> > thanks @oywino for writing that guide, I would never have got it installed and working without.
> 
> You're welcome. Have fun 😊
Thanks, man. That was really helpful

**Comment by FpazHn** [comment]
I have the following message when I go to HACS. 

You have 1 Lovelace elements that are not loaded properly in Lovelace.

It is related to config-editor. 

On the other hand --- the editor works great.

How do i get rid of the error? 

Thanks in advance.

**Comment by hros** [comment]
Hi,
Home-assistant UI has changed over the last three years since this issue has been posted
I downloaded both `config-editor` and `config-editor-card` form HACS and installed them
However, I'm unable to install the dashboard
Can you provide updated instructions?

**Comment by oywino** [comment]
> Can you provide updated instructions?
Sorry, but I can't. My add-on has worked 100% stable ever since, through all my HA updates. I very much depend on it, and don't like the idea of "tampering" with it.

**Comment by Macleykun** [comment]
> Hi, Home-assistant UI has changed over the last three years since this issue has been posted I downloaded both `config-editor` and `config-editor-card` form HACS and installed them However, I'm unable to install the dashboard Can you provide updated instructions?

just did it and you have to do it like so after you installed both and restart HA.

1. go into settings: 
![image](https://github.com/user-attachments/assets/afdcf692-8a73-4784-b03c-a3c45b28dc6b)
2. go into dashboards: 
![image](https://github.com/user-attachments/assets/ec76a261-88d2-4735-af90-bf25c7c79e80)
3. Click add dashboard:
![image](https://github.com/user-attachments/assets/7c6c8b30-c228-4aec-aee4-c53955bd75df)
4. Choose a new dashbaord from scratch
![image](https://github.com/user-attachments/assets/774b6da2-fde9-476d-a873-6d1f96bc3fb4)
5. Choose a name, an icon and you should have an extra dasbhoard to your right:
![image](https://github.com/user-attachments/assets/6cee784b-8258-41c7-a18c-174d87dd5ab5)
6. In the new dashboard, click on the pen icon where it says HOME:
![image](https://github.com/user-attachments/assets/2d4150eb-fe8c-4cb4-b105-2d49cfdd6511)
7. Choose under settings, Panel (single card). Save this.
![image](https://github.com/user-attachments/assets/4561a030-87dc-41ac-9682-d9b7b30957bc)
8. make a card:
![image](https://github.com/user-attachments/assets/09915fb4-5a05-4c38-85e1-649838650490)
9. Look for config:
![image](https://github.com/user-attachments/assets/4ceff223-9e8d-4aa6-a450-219ceda21578)
10. Click save:
![image](https://github.com/user-attachments/assets/fa522b9b-1796-4e3e-a7df-9623d53139f2)
11. Click done:
![image](https://github.com/user-attachments/assets/0bf9fd53-f142-4cb8-9b5f-c813a0903d06)
12. Choose a file you want to edit:
![image](https://github.com/user-attachments/assets/286f3732-04ba-47a7-9de9-f8442c1cdd42)
13. Make an edit, and hit Save in the bottom right:
![image](https://github.com/user-attachments/assets/0738723c-fc17-439d-96d9-0f4b93e736eb)

Enjoy your editor!
Sorry for the giant post.
Thanks to @oywino for the pdf, now it's using the full width!

**Comment by hros** [comment]
thanks @Macleykun !!!

**Comment by ea1dqe** [comment]
I can´t run the file editor. I do the steps, and the addon seems is correctly installed:
![image](https://github.com/user-attachments/assets/dc5180cb-0f6d-4b93-a638-4cfa69accbce)
However I don´t find the custom card, the frontend step seems to not work properly and does not create the card to install in the dashboard. ¿Any idea what could be the problem?

Many thank´s.

**Comment by ea1dqe** [comment]
I can run!!, but I´m not shure how... I am using docker in my installation and doing several tests I have found the following:
1. Initially I installed the integration (config editor) and the Dashboard (config editor card) from HACS.
2. The path in which it is installed is: '/config/custom_components/config_editor', but in my persistent docker folder that path does not exist.
3. A similar thing happens to me with the dashboard, the path where it was installed from HACS is '/config/www/community/config-editor-card', but in my docker persistent data folder that folder is not visible too.
4. If you manually download and install the files to the paths listed in the tutorial in the dockers persistent folder, you can find the paths of ..../custom_components/... and .../www/..., but even if you install the files, HA won't be able to use them.

![image](https://github.com/user-attachments/assets/549fcea1-acb4-4a28-a670-8895215b22ec)
5. Therefore, so that the card can be seen: custom:config-editor-card the path that must be configured in resources is /config/www/community/config-editor-card, which has nothing to do with the paths that are come inside the docker persistent folder.
So where are configurations, paths and files actually stored within Docker?
What is the actual path inside the container's persistent folder?
How is it possible that the .yaml files that I see in the root of this folder. they are look the same as those that the editor sees but the path is different? If you edit one of the .yaml files in the root docker directory, They have the same content, but the ones used by the editor or HA are in another path and are different.
![image](https://github.com/user-attachments/assets/e5fe8093-4e54-4667-ac89-29228aa66c1d)
And in the docker persistent folder:
![image](https://github.com/user-attachments/assets/11085385-4fc5-43c8-a558-c020be515acd)

![image](https://github.com/user-attachments/assets/fc3003e8-918f-49fe-9728-26bc10645810)
It works, but I'm not sure how the data and paths are managed in the docker persistent folder. 

All the best.

**Comment by oywino** [comment]
What type of HA installation do you have?

**Comment by ea1dqe** [comment]
Raspberry Pi 4, 4GB RAM, raspbian (Debian 12 Bookwrom), docker compose and HA container.
All files (system and containers) are install over externar USB hard disk, in fact, not SD card is insert on Raspi SD reader.
