### ISSUE TITLE
Yaml files in appdaemon not showing

### ISSUE THREAD

**Issue by andreibursuc97** [htmltiger/config-editor-card#30]
Hey, really nice feature helped me a lot. From the readme of the repo I understand that I should be able to edit all the .yaml files including those in subfolders, any idea why apps.yaml from appdaemon subfolder is not showing up in the list? Is this intended or a limitation?

**Comment by htmltiger** [comment]
It could be permission issue try and change the permission.

it scans 2 subfolders deep and excludes `custom_components` folder

Can you please try and change `custom_components/config_editor/__init__.py`

Line 52:
```
                if(p.count(os.sep) < 2) and p != 'custom_components':
```
and change 2 to 4 and restart HA

![image](https://user-images.githubusercontent.com/1429451/153721628-98def6cc-84a1-495d-b554-41d907b22e6e.png)

Edit:
It seems to be [permission of the appdaemon folder](https://github.com/thomasloven/hacs/blob/master/docs/usage/appdaemon.md)

**Comment by andreibursuc97** [comment]
Sorry, I just realised that the file didn’t even exist. I remembered checking it but I think I just saw the folder and I was like “hey, that’s apps.yaml” 😂. I’ve created it and now it shows up. Thank you for the fast answer.
