### ISSUE TITLE
Ability to list hidden files

### ISSUE THREAD

**Issue by thefunkygibbon** [htmltiger/config-editor-card#31]
Is there a way to view hidden files/search in hidden folders like .storage etc?  If not, would it be possible to allow for this (maybe as a tickbox option to do it for those who don't want to see those files?)

**Comment by htmltiger** [comment]
the files without valid extension would be difficult to implement in the current code as it searches for the files ending with the ext and the files you are talking about does not have any extension.

**Comment by htmltiger** [comment]
this is added in 4.1
