### ISSUE TITLE
Installed using HACS; shows the files but can only ENTER, not type

### ISSUE THREAD

**Issue by pdwonline** [htmltiger/config-editor-card#32]
I installed this and was able to open a config file. It displays the contents, but I cannot change a thing.
What I can do is add some empty lines by pressing enter, I can search for a file to edit, create a new one by selecting blank, and even save a file. But as soon as I enter some text, the show stops. I discovered this only applies to Safari..

**Comment by htmltiger** [comment]
Have you tried using the "basic editor" tickbox?

**Comment by htmltiger** [comment]
https://github.com/htmltiger/config-editor-card/issues/26

Try different browser / disable adblocker

**Comment by htmltiger** [comment]
closing due to no feedback

**Comment by fgonza2** [comment]
same issue here.    works only on "basic editor" mode

**Comment by pdwonline** [comment]
tried basic editor mode and that works..
