### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by Kdemontf** [htmltiger/config-editor-card#4]
I installed this HACS Integration, and it works well, really apreciated. However I would rather that it did not pull my !secrets.yaml file into the UI without at least ensuring I am the admin (I don't think it does by quick scan of the code), or even better asking for a password to be set/entered. Is there a way I can accomplish this? Thanks

**Comment by htmltiger** [comment]
Have you tried it?

It would not be possible to edit without admin user.
Create a user and try it

The custom component helper addon has the code for it.

**Comment by Kdemontf** [comment]
Thankyou, I just looked at the code quickly and did not see it, I did not test it, appreciate the quick response.
