### ISSUE TITLE
Read/Write back in VSCode

### ISSUE THREAD

**Issue by tamimology** [htmltiger/config-editor-card#42]
I think I had raised it before, it was resolved in #1 , and now it came back with a different issue

if the file's permissions are set to the following, then I cannot use it back in VSCode
-rw-r--r--  1 root root    7072 Apr 10 14:00 templates.yaml

The below examples work fine on both the card and VSCode

-rw-r--r--  1 1000  1000    484 Dec 13 21:22 zones.yaml
-rw-rw-rw-  1 root root     556 Feb 11 17:04 panel_iframe.yaml
-rw-rw-rw-  1 1000   911    151 Sep 10  2021 hacs.json
-rw-rw-rw-  1 root root     165 Jan 15 01:03 mqtt.yaml
-rwxrwxrwx  1 1000   911      0 Oct  6  2021 groups.yaml

**Comment by htmltiger** [comment]
could you please try 4.2 ?
