### ISSUE TITLE
Lovelace Dashboards doesn't have a Resources panel.

### ISSUE THREAD

**Issue by lezlikov** [htmltiger/config-editor-card#46]
I'm using HA without a supervisor and the Configuration -> Lovelace Dashboards doesn't have a Resources panel.
How do I get HA to see the config-editor-card.js file?
![screenShot](https://user-images.githubusercontent.com/73757896/196472385-30c5129d-b0c6-427e-8a7a-da3b215b8d56.png)

**Comment by htmltiger** [comment]
Enable advanced mode first.
![158922796-67abfc21-729b-49d3-af6f-15bd6d018b0a](https://user-images.githubusercontent.com/1429451/196479185-ea5d590b-c7b5-4c71-a1f0-00fb616bdbfe.png)

![Settings – Home Assistant](https://user-images.githubusercontent.com/1429451/196477643-94ad28fb-117f-4ae8-980d-803bf80a1119.png)
have a look here


https://github.com/htmltiger/config-editor-card/issues/29

**Comment by lezlikov** [comment]
Thank you. That helped.
