### ISSUE TITLE
Unable to edit in Safari

### ISSUE THREAD

**Issue by jdc0730** [htmltiger/config-editor-card#5]
Accessing my home assistant on a mac using Safari and am unable to edit and YAML files. It does pull them up and I am able to see them, but attempting to edit doesn't do anything (space seems to page down). It is working fine with Chrome on the same machine. Anything else I need to do for Safari?

**Comment by htmltiger** [comment]
have a look here
https://github.com/home-assistant/frontend/issues/10547
I don't have mac to test so cannot help.

Does the code editor for other dashboard items work?

**Comment by jdc0730** [comment]
It appears to be a different issue. Certain keys are working (return, tab, backspace) but others do not. Adding the -webkit-user-select:text to the div resolves the issue. That being said, I see you are using the standard ha-code-editor so not sure why it works in one area of the site but not here. It does seem to be working in the developer tools section which is the only place I have looked specifically.  I'll keep digging around.

**Comment by mortenjensen64** [comment]
Hi, I'm having the same issue on my iPhone. I can pull up the files but no cursor is showing. None of the keys work. This is happening using the companion app, safari, chrome, and edge. From my windows computer using edge everything works great.

**Comment by htmltiger** [comment]
Added a plain text editor for now

**Comment by mortenjensen64** [comment]
Very nice!  Confirming this is working. 

Regards,
Morten
