### ISSUE TITLE
Folder selector only 1 level deep

### ISSUE THREAD

**Issue by pdwonline** [htmltiger/config-editor-card#50]
I do have quite a lot of automations, and decided to split them apart. The config-editor-card becomes very handy, because the build-in editor doesn't support splitting the automation files. However, I discovered that I could not see all of my automations because I have a folder structure that is 3 levels deep.. That would not be a problem if I could configure the 'root' folder for the config-editor-card. Would it be possible to have such a feature?

**Comment by htmltiger** [comment]
try `depth: 5`

https://github.com/htmltiger/config-editor-card#advanced-config

**Comment by pdwonline** [comment]
Cool, thanx! Didn't know that option..
