### ISSUE TITLE
config editor in yaml mode

### ISSUE THREAD

**Issue by little-yo** [htmltiger/config-editor-card#59]
hello!
I installed config-editor & config-editor-card using HACS on my HA core.
Add config_editor: in configuration.yaml
I see integration in Settings-Integrations:
"This integration cannot be configured from the web interface because it was configured in YAML or was automatically added as a dependency by another integration"
![image](https://github.com/user-attachments/assets/989e77c1-f291-41eb-a87c-af9098b8a3fb)

And I see card record in Settings-Panel-Resources:
/hacsfiles/config-editor-card/config-editor-card.js  JavaScript module

But i still dont understand how to add sidebar for editing

**Comment by junkfix** [comment]
https://github.com/junkfix/config-editor-card?tab=readme-ov-file#add-in-the-sidebar

https://github.com/junkfix/config-editor-card/issues/29
