### ISSUE TITLE
Enhancement - Files list location 

### ISSUE THREAD

**Issue by tamimology** [htmltiger/config-editor-card#9]
You are doing really a great improvements on this wonderful card.

I just wanted to suggest if you can fix the location of files list at the bottom as it is moveable depending on the file content. Bit disturbing when opening files to move sight amd finger up and down and mid way. 
![Screenshot_20220111-135422_Home Assistant](https://user-images.githubusercontent.com/90429593/148873596-019bcfa6-ebb4-4a1a-9dd8-b07a48991cf2.png)
![Screenshot_20220111-135433_Home Assistant](https://user-images.githubusercontent.com/90429593/148873611-e4b4e730-fd42-43de-97c5-3064ae771d56.png)
![Screenshot_20220111-135452_Home Assistant](https://user-images.githubusercontent.com/90429593/148873624-6d54f3b4-79e9-4273-aee4-17eb199381a2.png)

**Comment by htmltiger** [comment]
Please try the updated version

**Comment by tamimology** [comment]
Perfect

Thanks
